#!/usr/bin/python
"""Takes a pickle of talks generated by talk_grabber and puts them in the db.

Usage:
  `PYTHONPATH="/home/colin/projects/django/" DJANGO_SETTINGS_MODULE="emmontoweb.settings" python insert_talks.py <talks_pickle_file>`

"""

import sys

if len(sys.argv) == 1:
  print __doc__
  sys.exit()

from talk_grabber import Talk
import pickle

#Adjusting for Jython 2.5.2
f = file(sys.argv[1], "r")
talks = pickle.load(f)
f.close()

from tagger.models import Talk as DBTalk

# Delete all existing talks.
DBTalk.objects.all().delete()

# Define id manually (because otherwise the database chooses).
for id in range(len(talks)):
  t = talks[id]
  DBTalk(id=id+1, title=t.title, authors=t.authors, start_time=t.start_time, end_time=t.end_time).save()
